server:
    contextPath: /projectnbs
spring:
    datasource:
        url: jdbc:mysql://localhost:3307/project_nbs
        username: root
        password: 6731
        driver-class-name: com.mysql.cj.jdbc.Driver

#    # Hibernate ddl auto (create, create-drop, validate, update)
# spring:
#    jpa:
#     hibernate: ddl-auto=update